#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash,
#       you should alter the first line of this file to use that shell, or
#       you may pass the correct shell to use when running the script.
#
#   (2) The scripts will be evaluated as is and inherit the environment
#       in which `$0` is called.  If you try to use the script in a different
#       shell however, change the `$(dirname "$0")` to `$(cd "$(dirname \"$0\")" && pwd)`.
#
#   (3) This script is generated by the Gradle build system.
#
#   (4) If using macOS, you may have encountered the error:
#       error: The system cannot find the path specified.
#       In that case you should change #!/bin/sh to #!/bin/bash
#       on the first line of gradlew.
#
##############################################################################

if [ -z "$JAVA_HOME" ] ; then
    JAVA_EXE="$(which java)"
    if [ -z "$JAVA_EXE" ] ; then
        echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        exit 1
    fi
else
    JAVA_EXE="$JAVA_HOME/bin/java"
fi
if ! command -v java >/dev/null 2>&1
then
    echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    exit 1
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $OSTYPE in
        linux*)
            MAX_FD_LIMIT=$( ulimit -H -n )
            if [ $? -eq 0 ] ; then
                if [ "$MAX_FD_LIMIT" != 'unlimited' ] ; then
                    ulimit -n $MAX_FD_LIMIT
                fi
            ;
            ;;
        darwin*)
            MAX_FD_LIMIT=$( ulimit -H -n )
            if [ $? -eq 0 ] ; then
                if [ "$MAX_FD_LIMIT" != 'unlimited' ] ; then
                    ulimit -n $MAX_FD_LIMIT
                fi
            fi
            ;;
    esac
fi

set -- "$@" "-Dorg.gradle.appname=$APP_BASE_NAME"

exec "$JAVA_EXE"  "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
